baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Homepage"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
theme = ["github.com/zwbetz-gh/cupper-hugo-theme"]
[module]
[[module.imports]]
  path = 'github.com/zwbetz-gh/cupper-hugo-theme'
[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "Blog"
url = "/post/"
weight = 2

[[menu.nav]]
name = "Bookmarks"
url = "/bookmark"
weight = 3